// <auto-generated />
using System;
using FC_EMDB.Database.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FC_EMDB.Migrations.Migrations
{
    [DbContext(typeof(DataBaseFcContext))]
    partial class DataBaseFcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FC_EMDB.Entities.Entities.Abonement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AbonementStatusId");

                    b.Property<int>("AbonementTypeId");

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("CountDays");

                    b.Property<DateTime>("DateOfRegistration");

                    b.Property<int>("Number");

                    b.HasKey("Id");

                    b.HasIndex("AbonementStatusId");

                    b.HasIndex("AbonementTypeId")
                        .IsUnique();

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Abonements");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.AbonementStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DaysCount");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AbonementStatuses");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.AbonementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AbonementTypes");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.CoachTraining", b =>
                {
                    b.Property<int>("CoachId");

                    b.Property<int>("TrainingId");

                    b.HasKey("CoachId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("CoachTrainings");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.Human", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirdth");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<byte[]>("Photo");

                    b.HasKey("Id");

                    b.ToTable("Human");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Human");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.PreRegistration", b =>
                {
                    b.Property<int>("TrainingId");

                    b.Property<int>("AbonementId");

                    b.HasKey("TrainingId", "AbonementId");

                    b.HasIndex("AbonementId");

                    b.ToTable("PreRegistrations");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusyPlacesCount");

                    b.Property<DateTime>("EndTime");

                    b.Property<int>("FreePlacesCount");

                    b.Property<int>("GymId");

                    b.Property<bool>("IsFinished");

                    b.Property<bool>("IsMustPay");

                    b.Property<bool>("IsNewTraining");

                    b.Property<bool>("IsReplaced");

                    b.Property<bool>("Ispopular");

                    b.Property<string>("LevelName");

                    b.Property<int>("PlacesCount");

                    b.Property<string>("ProgramType");

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("TrainingName");

                    b.Property<string>("mDescription");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.TrainingAbonement", b =>
                {
                    b.Property<int>("TrainingId");

                    b.Property<int>("AbonementId");

                    b.Property<DateTime>("ComeInTime");

                    b.Property<DateTime>("ComeOutTime");

                    b.HasKey("TrainingId", "AbonementId");

                    b.HasIndex("AbonementId");

                    b.ToTable("TrainingAbonements");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.Client", b =>
                {
                    b.HasBaseType("FC_EMDB.Entities.Entities.Human");

                    b.Property<int>("Login");

                    b.Property<string>("PasportData");

                    b.Property<string>("PasswordHash");

                    b.ToTable("Client");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.Employee", b =>
                {
                    b.HasBaseType("FC_EMDB.Entities.Entities.Human");

                    b.Property<string>("Desc");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("Employee_Login")
                        .HasMaxLength(50);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnName("Employee_PasswordHash")
                        .HasMaxLength(50);

                    b.ToTable("Employee");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.Coach", b =>
                {
                    b.HasBaseType("FC_EMDB.Entities.Entities.Employee");


                    b.ToTable("Coach");

                    b.HasDiscriminator().HasValue("Coach");
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.Abonement", b =>
                {
                    b.HasOne("FC_EMDB.Entities.Entities.AbonementStatus", "AbonementStatus")
                        .WithMany("Abonements")
                        .HasForeignKey("AbonementStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FC_EMDB.Entities.Entities.AbonementType", "AbonementType")
                        .WithOne("Abonement")
                        .HasForeignKey("FC_EMDB.Entities.Entities.Abonement", "AbonementTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FC_EMDB.Entities.Entities.Client", "Client")
                        .WithOne("Abonement")
                        .HasForeignKey("FC_EMDB.Entities.Entities.Abonement", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.CoachTraining", b =>
                {
                    b.HasOne("FC_EMDB.Entities.Entities.Coach", "Coach")
                        .WithMany("CoachTrainings")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FC_EMDB.Entities.Entities.Training", "Training")
                        .WithMany("CoachTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.PreRegistration", b =>
                {
                    b.HasOne("FC_EMDB.Entities.Entities.Abonement", "Abonement")
                        .WithMany("PreRegistrations")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FC_EMDB.Entities.Entities.Training", "Training")
                        .WithMany("PreRegistrations")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.Training", b =>
                {
                    b.HasOne("FC_EMDB.Entities.Entities.Gym", "Gym")
                        .WithMany("Trainings")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FC_EMDB.Entities.Entities.TrainingAbonement", b =>
                {
                    b.HasOne("FC_EMDB.Entities.Entities.Abonement", "Abonement")
                        .WithMany("TrainingAbonements")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FC_EMDB.Entities.Entities.Training", "Training")
                        .WithMany("TrainingAbonements")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
